#!/bin/bash

#install dependencies
sudo apt -y install --no-install-recommends apt-transport-https ca-certificates curl gnupg2

#install docker
. /etc/os-release
curl -fsSL https://download.docker.com/linux/${ID}/gpg | sudo apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt update
sudo apt -y install docker-ce docker-ce-cli containerd.io

#add user to docker group
sudo usermod -aG docker $USER

#create docker start script
mkdir -p ~/bin
dd of=~/bin/docker-service << EOF
#!/bin/bash
DOCKER_DIR=/var/run/
DOCKER_SOCK="$DOCKER_DIR/docker.sock"
export DOCKER_HOST="unix://$DOCKER_SOCK"
nohup sudo -b dockerd < /dev/null > ~/dockerd.log 2>&1
EOF
chmod +x ~/bin/docker-service

#start docker deamon without typing sudo password
LINE="%docker ALL=(ALL) NOPASSWD: /usr/bin/dockerd"
FILE=/etc/sudoers
sudo grep -qF -- "$LINE" "$FILE" || echo $LINE | sudo EDITOR='tee -a' visudo

#autostart docker 
LINE="~/bin/docker-service"
FILE=~/.profile
grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
